spring:
  application:
    name: boardproject

  datasource:
    url: jdbc:mysql://localhost:3306/liondb
    username: zdni
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
